"use client";
import {useCallback,useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
const tabs=["Live","Score","Leaderboard","Chat"];
export default function App(){
 const [ready,setReady]=useState(false),[err,setErr]=useState(""),[players,setPlayers]=useState([]),[teams,setTeams]=useState([]),[rounds,setRounds]=useState([]),[scores,setScores]=useState([]),[msgs,setMsgs]=useState([]),[me,setMe]=useState(null),[tab,setTab]=useState("Live"),[rn,setRn]=useState(1),[hole,setHole]=useState(1),[draft,setDraft]=useState({}),[chat,setChat]=useState("");
 const load=useCallback(async()=>{let [p,t,r,s,m]=await Promise.all([supabase.from("players").select("*").order("name"),supabase.from("teams").select("*").order("name"),supabase.from("rounds").select("*,courses(name)").order("round_number"),supabase.from("hole_scores").select("*"),supabase.from("messages").select("*").order("created_at",{ascending:false}).limit(100)]);let e=p.error||t.error||r.error||s.error||m.error;if(e)throw e;setPlayers(p.data||[]);setTeams(t.data||[]);setRounds(r.data||[]);setScores(s.data||[]);setMsgs(m.data||[])},[]);
 useEffect(()=>{(async()=>{try{let {data:{session}}=await supabase.auth.getSession();if(!session){let x=await supabase.auth.signInAnonymously();if(x.error)throw x.error}await load();let id=localStorage.getItem("jander-player");if(id){let x=await supabase.from("players").select("*").eq("id",id).maybeSingle();if(x.data)setMe(x.data)}}catch(e){setErr(e.message)}finally{setReady(true)}})()},[load]);
 useEffect(()=>{if(!ready)return;let c=supabase.channel("jander-live").on("postgres_changes",{event:"*",schema:"public",table:"hole_scores"},load).on("postgres_changes",{event:"*",schema:"public",table:"messages"},load).subscribe();return()=>supabase.removeChannel(c)},[ready,load]);
 const round=rounds.find(x=>x.round_number==rn);
 async function save(){try{let {data:{user}}=await supabase.auth.getUser();let rows=players.filter(p=>draft[p.id]).map(p=>({round_id:round.id,player_id:p.id,hole_number:+hole,gross_score:+draft[p.id],entered_by:user.id}));if(!rows.length)throw Error("Enter at least one score.");let x=await supabase.from("hole_scores").upsert(rows,{onConflict:"round_id,player_id,hole_number"});if(x.error)throw x.error;setDraft({});await load();if(hole<18)setHole(hole+1);setTab("Live")}catch(e){setErr(e.message)}}
 async function send(){if(!chat.trim())return;try{let {data:{user}}=await supabase.auth.getUser();let x=await supabase.from("messages").insert({tournament_id:me.tournament_id,player_id:me.id,auth_user_id:user.id,body:chat.trim()});if(x.error)throw x.error;setChat("")}catch(e){setErr(e.message)}}
 if(!ready)return <main className="join"><h1>JANDER CUP</h1><p>Connecting…</p></main>;
 if(!me)return <main className="join"><p className="gold">CRANBROOK • 2026</p><h1>JANDER CUP</h1><p>Choose your golfer.</p>{err&&<div className="error">{err}</div>}<div className="grid">{players.map(p=><button key={p.id} onClick={()=>{localStorage.setItem("jander-player",p.id);setMe(p)}}><b>{p.name}</b><small>HCP {p.handicap}</small></button>)}</div></main>;
 return <main className="shell"><header><div><p className="gold">JANDER CUP 2026</p><h2>{tab}</h2></div><button className="pill" onClick={()=>{localStorage.removeItem("jander-player");setMe(null)}}>{me.name.split(" ")[0]}</button></header>{err&&<div className="error">{err}</div>}
 {tab==="Live"&&<><div className="hero"><p className="gold">LIVE TOURNAMENT</p><h1>JANDER CUP</h1><p>Cranbrook, British Columbia</p></div><Card title="Course Rotation">{rounds.map(r=><div className="row" key={r.id}><b>R{r.round_number}</b><span>{r.courses?.name}</span><small>{fmt(r.format)}</small></div>)}</Card><Card title="Recent Scores">{scores.slice(-10).reverse().map(s=><div className="row" key={s.id}><b>{players.find(p=>p.id===s.player_id)?.name}</b><span>#{s.hole_number}</span><strong>{s.gross_score}</strong></div>)}{!scores.length&&<p>No scores yet.</p>}</Card></>}
 {tab==="Score"&&<><div className="controls"><select value={rn} onChange={e=>setRn(+e.target.value)}>{rounds.map(r=><option key={r.id} value={r.round_number}>Round {r.round_number} — {fmt(r.format)}</option>)}</select><select value={hole} onChange={e=>setHole(+e.target.value)}>{[...Array(18)].map((_,i)=><option key={i}>{i+1}</option>)}</select></div><Card title={`Round ${rn} • Hole ${hole}`}><p>{round?.courses?.name}</p>{teams.map(t=><div key={t.id}><h3 className="gold">{t.name}</h3>{players.filter(p=>p.team_id===t.id).map(p=>{let old=scores.find(s=>s.round_id===round?.id&&s.player_id===p.id&&s.hole_number==hole);return <label className="score" key={p.id}><span><b>{p.name}</b><small>HCP {p.handicap}</small></span><input type="number" min="1" max="20" placeholder={old?.gross_score||"—"} value={draft[p.id]||""} onChange={e=>setDraft({...draft,[p.id]:e.target.value})}/></label>})}</div>)}<button className="primary" onClick={save}>Save Hole</button></Card></>}
 {tab==="Leaderboard"&&<Card title="Live Gross Totals">{players.map(p=>{let ps=scores.filter(s=>s.player_id===p.id);return <div className="row" key={p.id}><b>{p.name}</b><span>{ps.length} scores</span><strong>{ps.reduce((a,b)=>a+(b.gross_score||0),0)||"—"}</strong></div>})}</Card>}
 {tab==="Chat"&&<Card title="Tournament Chat"><div className="messages">{msgs.map(m=><div className="msg" key={m.id}><b>{players.find(p=>p.id===m.player_id)?.name||"Jander Cup"}</b><p>{m.body}</p></div>)}</div><div className="chat"><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Talk some trash…"/><button onClick={send}>Send</button></div></Card>}
 <nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav></main>
}
function Card({title,children}){return <section className="card"><h3>{title}</h3>{children}</section>}
function fmt(x){return({best_ball:"Best Ball",scramble:"Scramble",high_low:"High / Low",individual:"Individual"})[x]||x}
